package com.qinggan.app.arielapp.minor.integration;

import com.tencent.qqmusic.third.api.contract.PlayState;

import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_API_ILLEGAL_ARGUMENT;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_API_INTERRUPTED;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_API_NOT_INITIALIZED;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_API_NO_PERMISSION;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_API_UNKNOWN;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_API_UNSUPPORTED_ACTION;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_FAILED_TO_QUERY_FROM_MID;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_FAILED_TO_QUERY_FROM_SONG_ID;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_GET_DATA_ARGUMENT;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_GET_DATA_INNER;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_GET_DATA_NETWORK;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_NEED_USER_AUTHENTICATION;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_PLAY_LIST_TOO_LONG;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_PLAY_NO_MEDIA;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_PLAY_NO_NETWORK;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_PLAY_NO_PERMISSION;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_PLAY_NO_STORAGE;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_PLAY_OPERATOR_NETWORK;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_PLAY_OVER_SEA_FORBIDDEN;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_PLAY_PLAYER_ERROR;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_PLAY_TOO_OFTEN;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_PLAY_UNKNOWN;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_SERVICE_INITIATING_TIMEOUT;
import static com.tencent.qqmusic.third.api.contract.ErrorCodes.ERROR_SERVICE_NOT_READY;

public class MusicContacts {
    public static final int NOMALSUCCESSCODE = 0;
    public static final int NOMALERRORCODE = -1;
    public static final long NOMALLONGERRORCODE = -1L;
    public static final int PLAYSTARTED = PlayState.STARTED;
    public static final int PLAYPAUSED = PlayState.PAUSED;
    public static final int PLAYPAUSING = PlayState.PAUSING;
    public static final int PLAYIDLE = PlayState.IDLE;
    public static final int PLAYINIT = PlayState.INITIALIZED;
    public static final int PLAYSTOPPED = PlayState.STOPPED;
    public static final int PLAYEND = PlayState.END;
    public static final int PLAYPREPARED = PlayState.PREPARED;
    public static final String PLAYCMD = "playMusic";
    public static final String RESUMECMD = "resumeMusic";
    public static final String NEXTCMD = "skipToNext";
    public static final String PREVCMD = "skipToPrevious";
    public static final String STOPCMD = "stopMusic";
    public static final String SETPLAYMODECMD = "setPlayMode";
    public static final String SEARCHCMD = "search";
    public static final String ADDLOCALPATHTOFAVCMD = "addLocalPathToFavourite";
    public static final String ADDTOFAVCMD = "addToFavourite";
    public static final String ISFAVLOCALPATHCMD = "isFavouriteLocalPath";
    public static final String ISFAVMIDCMD = "isFavouriteMid";
    public static final String REMOVEFROMFAVCMD = "removeFromFavourite";
    public static final String REMOVELOCALPATHFROMFAVCMD = "removeLocalPathFromFavourite";
    public static final String GETFOLDERLISTCMD = "getFolderList";
    public static final String GETPLAYLISTCMD = "getPlayList";
    public static final String GETSONGLISTCMD = "getSongList";
    public static final String PLAYSONGIDCMD = "playSongId";
    public static final String PLAYSONGIDATINDEXCMD = "playSongIdAtIndex";
    public static final String PLAYSONGLOCALPATHCMD = "playSongLocalPath";
    public static final String PLAYSONGMIDCMD = "playSongMid";
    public static final String PLAYSONGMIDATINDEXCMD = "playSongMidAtIndex";
    public static final String GETPLAYBACKSTATECMD = "getPlaybackState";
    public static final String GETCURRENTSONGCMD = "getCurrentSong";
    public static final String GETCURRENTTIMECMD = "getCurrTime";
    public static final String GETPLAYMODECMD = "getPlayMode";
    public static final String GETTOTALTIMECMD = "getTotalTime";
    public static final String HICMD = "hi";
    public static final String PAUSECMD = "pauseMusic";
    public static final String GETFAVFOLDERIDCMD = "getFavouriteFolderId";
    public static final String QQINTENT = "com.tencent.qqmusic.third.api.QQMusicApiService";
    public static final String QQPACKAGE = "com.tencent.qqmusic";
    public static final String RETURNCODEPARAMS = "code";
    public static final String RETURNDATAPARAMS = "data";
    public static final String PARAMSMIDLIST = "midList";
    public static final String PARAMSINDEX = "index";
    public static final String PARAMSPATHLIST = "pathList";
    public static final String PARAMSSONGIDLIST = "songIdList";
    public static final String PARAMSFOLDERID = "folderId";
    public static final String PARAMSFOLDERTYPE = "folderType";
    public static final String PARAMSPAGE = "page";
    public static final String PARAMSLOCALPATHLIST = "localPathList";
    public static final String PARAMSFIRSTPAGE = "firstPage";
    public static final String PARAMSSEARCHTYPE = "searchType";
    public static final String PARAMSKEYWORD = "keyword";
    public static final String PARAMSPLAYMODE = "playMode";
    public static final String PARAMSCALLBACKURL = "qqmusicapidemo://xxx";
    public static final int PARAMINDEXINV = -1;
    public static final String OPSTYPESEARCHKEY = "searchMusicByKey";
    public static final String OPSTYPEGETVER = "getVersion";
    public static final String OPSTYPELOGINQQMUSIC = "loginQQMusic";
    public static final String OPSTYPEOPENQQMUSIC = "openQQMusic";
    public static final String OPSTYPEADDTOFAV = "addToFavouriteAlias";
    public static final int MODEGETFOLDERLIST = 0;
    public static final int MODEGETPLAYLIST = 1;
    public static final int MODEGETSONGLIST = 2;
    public static final int MODEPLAYSONGID = 0;
    public static final int MODEPLAYSONGLOCALPATH = 1;
    public static final int MODEPLAYSONGMID = 2;
    public static final String TYPEUNKNOW = "uknow";
    public static final String OPPO = "OPPO";
    public static final int MESSAGEGETRANK = 0;
    public static final int MESSAGEGETRECOMMEND =1;
    public static final int MESSAGEGETMY_FOLDER = 2;
    public static final int MESSAGEGETPLAYLIST = 3;
    public static final int MESSAGEGETRANKNEWMUSIC = 4;
    public static final int TYPEFOLDERPLAYLIST = 66;
    public static final int TYPELISTNEWMUSIC = 88;
    public static final int MEDDAGEOFFLINESEARCH = 77;
    public static final int MESSAGEGETLOVEMUSIC = 0x220;
    public static final int MESSAGEGETTOPMUSIC = 0x221;
    public static final int MESSAGEGETNEWMUSIC = 0x222;
    public static final int MESSAGE_PLAY_NEXT_SONG = 0x300;
    public static final int MESSAGE_FIRST_PLAY_NEW = 0x301;
    public static final int MESSAGE_SEND_LIST = 0x302;
    public static final int MESSAGE_PLAY_OFFLINE_SEARCH = 0x555;
    public static final String KEYLASTSONGTITLE = "lastSong_Title";
    public static final String KEYLASTSONGID = "lastSong_Id";
    public static final String KEYLASTSONGMID = "lastSong_Mid";
    public static final String KEYLASTSONGCOVERURI = "lastSong_Album_CoverUri";
    public static final String KEYLASTSONGALBUMTITLE = "lastSong_Album_Title";
    public static final String KEYLASTSONGALBUMID = "lastSong_Album_Id";
    public static final String KEYLASTSONGSINGERID = "lastSong_Singer_Id";
    public static final String KEYLASTSONGSINGERTITLE= "lastSong_Singer_Title";
    public static final String DEFAULT_FILE = "music_save.xml";
    public static final String EMPTYSTRINGVALUE = "";
    public static final String SPACESTRINGVALUE = " ";
    public static final String UNKNOWSTRINGVALUE = "UNKNOW";
    public static final String KEYOLDSONGTITLE = "oldSong_Title";
    public static final String KEYOLDSONGID = "oldSong_Id";
    public static final String KEYOLDSONGMID = "oldSong_Mid";
    public static final String KEYOLDSONGCOVERURI = "oldSong_Album_CoverUri";
    public static final String KEYOLDSONGALBUMTITLE = "oldSong_Album_Title";
    public static final String KEYOLDSONGALBUMID = "oldSong_Album_Id";
    public static final String KEYOLDSONGSINGERID = "oldSong_Singer_Id";
    public static final String KEYOLDSONGSINGERTITLE = "oldSong_Singer_Title";
    public static final String KEYOLDLIST = "m_old_list";
    public static final String KEYQQMUSIC = "qqmusic";
    public static final int LOCALLISTURI = 0;
    public static final int LOCALLISTID = 1;
    public static final int LOCALLISTTITLE = 2;
    public static final int LOCALLISTALBUM = 3;
    public static final int LOCALLISTARTIST = 4;
    public static final int LOCALLISTDURATION = 5;
    public static final long STATE_CHANGE_GAP = 1200;
    public static final long STATE_CHANGE_COUNT = 3;
    public static final String LOCAL_MUSIC = "本地音乐";
    public static final String NEW_MUSIC = "新歌榜";
    public static final String TOP_MUSIC = "流行指数榜";
    public static final String LIVE_MUSIC = "我喜欢";
    public static final int ERROR_CODE_NO_PERMISSION = ERROR_PLAY_NO_PERMISSION;
    public static final long PERMISSION_HINT_MIN_SKIP_TIME = 6000L;

    public static final int REQUEST_ERROR_CODE_ILLEGAL_ARGUMENT = ERROR_API_ILLEGAL_ARGUMENT;
    public static final int REQUEST_ERROR_CODE_INTERRUPTED = ERROR_API_INTERRUPTED;
    public static final int REQUEST_ERROR_CODE_NO_PERMISSION = ERROR_API_NO_PERMISSION;
    public static final int REQUEST_ERROR_CODE_NOT_INITIALIZED = ERROR_API_NOT_INITIALIZED;
    public static final int REQUEST_ERROR_CODE_UNKNOWN = ERROR_API_UNKNOWN;
    public static final int REQUEST_ERROR_CODE_UNSUPPORTED_ACTION = ERROR_API_UNSUPPORTED_ACTION;
    public static final int REQUEST_ERROR_CODE_FAILED_TO_QUERY_FROM_MID = ERROR_FAILED_TO_QUERY_FROM_MID;
    public static final int REQUEST_ERROR_CODE_FAILED_TO_QUERY_FROM_SONG_ID = ERROR_FAILED_TO_QUERY_FROM_SONG_ID;
    public static final int REQUEST_ERROR_CODE_DATA_ARGUMENT = ERROR_GET_DATA_ARGUMENT;
    public static final int REQUEST_ERROR_CODE_DATA_INNER = ERROR_GET_DATA_INNER;
    public static final int REQUEST_ERROR_CODE_DATA_NETWORK = ERROR_GET_DATA_NETWORK;
    public static final int REQUEST_ERROR_CODE_AUTHENTICATION = ERROR_NEED_USER_AUTHENTICATION;
    public static final int REQUEST_ERROR_CODE_LIST_TOO_LONG = ERROR_PLAY_LIST_TOO_LONG;
    public static final int REQUEST_ERROR_CODE_NO_MEDIA = ERROR_PLAY_NO_MEDIA;
    public static final int REQUEST_ERROR_CODE_NO_NETWORK = ERROR_PLAY_NO_NETWORK;
    public static final int REQUEST_ERROR_CODE_NO_PLAY_PERMISSION = ERROR_PLAY_NO_PERMISSION;
    public static final int REQUEST_ERROR_CODE_NO_STORAGE = ERROR_PLAY_NO_STORAGE;
    public static final int REQUEST_ERROR_CODE_OPERATOR_NETWORK = ERROR_PLAY_OPERATOR_NETWORK;
    public static final int REQUEST_ERROR_CODE_OVER_SEA_FORBIDDEN = ERROR_PLAY_OVER_SEA_FORBIDDEN;
    public static final int REQUEST_ERROR_CODE_PLAYER_ERROR = ERROR_PLAY_PLAYER_ERROR;
    public static final int REQUEST_ERROR_CODE_TOO_OFTEN = ERROR_PLAY_TOO_OFTEN;
    public static final int REQUEST_ERROR_CODE_PLAY_UNKNOWN = ERROR_PLAY_UNKNOWN;
    public static final int REQUEST_ERROR_CODE_SERVICE_INITIATING_TIMEOUT = ERROR_SERVICE_INITIATING_TIMEOUT;
    public static final int REQUEST_ERROR_CODE_SERVICE_NOT_READY = ERROR_SERVICE_NOT_READY;
}
